package raum.controllers;

import common.dto.BasicCredentialDTO;
import common.dto.CredentialsDTO;
import common.exception.ErrorResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.security.SecurityRequirements;
import io.swagger.v3.oas.annotations.tags.Tag;
import common.exception.UnauthorizedException;
import org.springframework.security.core.context.ReactiveSecurityContextHolder;
import org.springframework.web.bind.annotation.*;
import raum.openbao.OpenBaoService;
import raum.services.CredentialsService;
import reactor.core.publisher.Mono;

@RestController
@RequestMapping("/credentials")
@Tag(name = "Credentials", description = "Database credential management backed by OpenBao dynamic secrets")
class CredentialsController {
    final CredentialsService credentialsService;
    final OpenBaoService openBaoService;

    public CredentialsController(CredentialsService credentialsService, OpenBaoService openBaoService) {
        this.credentialsService = credentialsService;
        this.openBaoService = openBaoService;
    }

    @Operation(
            summary = "Issue ephemeral database credentials",
            description = "Returns short-lived database credentials for the given org and service, generated by OpenBao's dynamic secrets engine. " +
                    "The response includes the connection details (host, port, dbName, dbEngine) alongside the ephemeral username and password. " +
                    "leaseId and leaseDuration (seconds) are the OpenBao lease. Credentials expire when the lease does. " +
                    "Authentication: either a valid JWT (Authorization: Bearer) or an X-Vault-Token header is accepted. " +
                    "The X-Vault-Token path is for OpenBao AppRole-authenticated callers (e.g. Vassago during login) that do not hold a user JWT."
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Ephemeral credentials issued"),
            @ApiResponse(responseCode = "401", description = "No valid JWT or Vault token provided", content = @Content(schema = @Schema(implementation = ErrorResponse.class))),
            @ApiResponse(responseCode = "404", description = "No registered credentials found for this org/service pair", content = @Content(schema = @Schema(implementation = ErrorResponse.class)))
    })
    @SecurityRequirements({
            @SecurityRequirement(name = "bearerAuth"),
            @SecurityRequirement(name = "vaultToken")
    })
    @PostMapping("/ephemeral")
    public Mono<CredentialsDTO> getCredentialsForOrgAndService(
            @Parameter(description = "OpenBao AppRole token, accepted as an alternative to a JWT") @RequestHeader(value = "X-Vault-Token", required = false) String vaultToken,
            @RequestBody BasicCredentialDTO requestDTO) {
        return ReactiveSecurityContextHolder.getContext()
                .map(ctx -> ctx.getAuthentication())
                .filter(auth -> auth != null && auth.isAuthenticated())
                .flatMap(auth -> credentialsService.getEphemeralCredentialsByOrgIdAndServiceId(requestDTO))
                .switchIfEmpty(Mono.defer(() -> {
                    if (vaultToken != null) {
                        return openBaoService.validateToken(vaultToken)
                                .flatMap(valid -> valid
                                        ? credentialsService.getEphemeralCredentialsByOrgIdAndServiceId(requestDTO)
                                        : Mono.error(new UnauthorizedException("Invalid token")));
                    }
                    return Mono.error(new UnauthorizedException("Authentication required"));
                }));
    }

    @Operation(summary = "Health check", description = "Returns true if Raum's own database is reachable. Internal use only.")
    @ApiResponse(responseCode = "200", description = "Database reachable")
    @SecurityRequirement(name = "bearerAuth")
    @GetMapping("/test-db")
    public Mono<Boolean> testDb() {
        return credentialsService.testDB();
    }

    @Operation(
            summary = "Register database credentials",
            description = "Stores static database credentials for an org/service pair and registers the database connection with OpenBao's dynamic secrets engine. " +
                    "After registration, callers should use POST /credentials/ephemeral instead of these static credentials. " +
                    "Cannot be used to register credentials for Raum itself. Requires RAUM_MANAGE."
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Credentials registered — returns orgId and serviceId only; static credentials are not echoed back"),
            @ApiResponse(responseCode = "400", description = "Invalid request body", content = @Content(schema = @Schema(implementation = ErrorResponse.class))),
            @ApiResponse(responseCode = "401", description = "Missing or invalid JWT", content = @Content(schema = @Schema(implementation = ErrorResponse.class))),
            @ApiResponse(responseCode = "403", description = "Insufficient permissions or attempt to register credentials for Raum", content = @Content(schema = @Schema(implementation = ErrorResponse.class)))
    })
    @SecurityRequirement(name = "bearerAuth")
    @PostMapping
    public Mono<BasicCredentialDTO> saveCredentials(@RequestBody CredentialsDTO credentials) {
        return credentialsService.saveNewCredentials(credentials);
    }
}
