package raum.controllers;

import common.dto.BasicCredentialDTO;
import common.dto.CredentialsDTO;
import common.exception.ErrorResponse;
import common.exception.ForbiddenException;
import common.grants.NoTierForRolesException;
import common.grants.ServiceGrantProfiles;
import common.grants.ServiceTier;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.security.SecurityRequirements;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.ReactiveSecurityContextHolder;
import org.springframework.security.core.context.SecurityContext;
import org.springframework.web.bind.annotation.*;
import raum.openbao.OpenBaoService;
import raum.openbao.ServiceIdentity;
import raum.security.RaumAuthentication;
import raum.security.RaumPermission;
import raum.services.CredentialsService;
import raum.services.ServiceNameResolver;
import reactor.core.publisher.Mono;

import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@RestController
@RequestMapping("/credentials")
@Tag(name = "Credentials", description = "Database credential management backed by OpenBao dynamic secrets")
class CredentialsController {

    final CredentialsService credentialsService;
    final OpenBaoService openBaoService;
    final ServiceNameResolver serviceNameResolver;
    private final Map<ServiceIdentity, UUID> serviceIdByIdentity;

    public CredentialsController(CredentialsService credentialsService,
                                OpenBaoService openBaoService,
                                ServiceNameResolver serviceNameResolver,
                                @Value("${bime.service-id}") String bimeServiceId,
                                @Value("${vassago.service-id}") String vassagoServiceId) {
        this.credentialsService = credentialsService;
        this.openBaoService = openBaoService;
        this.serviceNameResolver = serviceNameResolver;
        this.serviceIdByIdentity = new EnumMap<>(ServiceIdentity.class);
        this.serviceIdByIdentity.put(ServiceIdentity.BIME, UUID.fromString(bimeServiceId));
        this.serviceIdByIdentity.put(ServiceIdentity.VASSAGO, UUID.fromString(vassagoServiceId));
    }

    @Operation(
            summary = "Issue ephemeral database credentials",
            description = "Returns short-lived database credentials for the given org and service, generated by OpenBao's " +
                    "dynamic secrets engine. The response includes connection details (host, port, dbName, dbEngine), the " +
                    "ephemeral username/password, the OpenBao lease (leaseId, leaseDuration seconds), and the issued grant " +
                    "tier. This endpoint is service-to-service only: every request must carry a valid X-Vault-Token that " +
                    "belongs to a recognised service AppRole (raum-service / vassago / bime). A bare user JWT, a root token, " +
                    "or any stray token is refused. " +
                    "When a JWT is also present, it supplies the org and the caller's roles; those roles resolve to one of " +
                    "five Postgres tiers (catalog/readonly/sales/operations/full) enforced at the DB-role level, so e.g. a " +
                    "BIME_CASHIER connection physically cannot UPDATE products even from a raw client. A bime/vassago service " +
                    "token may only request its own service's credentials; requesting another org's credentials via JWT " +
                    "requires CREDENTIAL_MANAGE (issued at the full tier). A raum-service token is the platform orchestrator " +
                    "and may request any org/service at the full tier."
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Ephemeral credentials issued"),
            @ApiResponse(responseCode = "401", description = "Missing X-Vault-Token, or it is not a recognised service AppRole token", content = @Content(schema = @Schema(implementation = ErrorResponse.class))),
            @ApiResponse(responseCode = "403", description = "Service token / JWT not permitted for the requested org or service, or the JWT holds no role for the requested service", content = @Content(schema = @Schema(implementation = ErrorResponse.class))),
            @ApiResponse(responseCode = "404", description = "No registered credentials found for this org/service pair", content = @Content(schema = @Schema(implementation = ErrorResponse.class)))
    })
    @SecurityRequirements({
            @SecurityRequirement(name = "bearerAuth"),
            @SecurityRequirement(name = "vaultToken")
    })
    @PostMapping("/ephemeral")
    public Mono<CredentialsDTO> getCredentialsForOrgAndService(
            @Parameter(description = "Service AppRole token — mandatory on every call") @RequestHeader(value = "X-Vault-Token", required = false) String vaultToken,
            @RequestBody BasicCredentialDTO requestDTO) {
        return openBaoService.resolveServiceToken(vaultToken)
                .flatMap(identity -> ReactiveSecurityContextHolder.getContext()
                        .map(SecurityContext::getAuthentication)
                        .filter(auth -> auth != null && auth.isAuthenticated())
                        .flatMap(auth -> issueWithJwt(auth, identity, requestDTO))
                        .switchIfEmpty(Mono.defer(() -> issueServiceOnly(identity, requestDTO))));
    }

    /** No user JWT — the caller is a service acting as itself (vassago login, bime schedulers). */
    private Mono<CredentialsDTO> issueServiceOnly(ServiceIdentity identity, BasicCredentialDTO requestDTO) {
        if (identity != ServiceIdentity.RAUM && !ownsRequestedService(identity, requestDTO)) {
            return Mono.error(new ForbiddenException("Service token may only request its own service's credentials"));
        }
        return credentialsService.getEphemeralCredentialsByOrgIdAndServiceId(requestDTO, ServiceTier.FULL);
    }

    private Mono<CredentialsDTO> issueWithJwt(Authentication auth, ServiceIdentity identity,
                                             BasicCredentialDTO requestDTO) {
        if (identity != ServiceIdentity.RAUM && !ownsRequestedService(identity, requestDTO)) {
            return Mono.error(new ForbiddenException("Service token may only request its own service's credentials"));
        }

        boolean canManage = auth.getAuthorities().stream()
                .anyMatch(a -> a.getAuthority().equals(RaumPermission.CREDENTIAL_MANAGE.name()));
        if (canManage) {
            return credentialsService.getEphemeralCredentialsByOrgIdAndServiceId(requestDTO, ServiceTier.FULL);
        }

        if (!(auth instanceof RaumAuthentication raumAuth) || !raumAuth.getOrgId().equals(requestDTO.getOrgId())) {
            return Mono.error(new ForbiddenException("CREDENTIAL_MANAGE required to request another org's credentials"));
        }

        List<String> rolesForService = raumAuth.getRoles().getOrDefault(
                String.valueOf(requestDTO.getServiceId()), List.of());

        return serviceNameResolver.nameFor(requestDTO.getServiceId())
                .flatMap(serviceName -> {
                    ServiceTier tier;
                    try {
                        tier = ServiceGrantProfiles.forServiceName(serviceName).resolveTier(rolesForService);
                    } catch (NoTierForRolesException e) {
                        return Mono.error(new ForbiddenException("No role held for the requested service"));
                    }
                    return credentialsService.getEphemeralCredentialsByOrgIdAndServiceId(requestDTO, tier);
                });
    }

    private boolean ownsRequestedService(ServiceIdentity identity, BasicCredentialDTO requestDTO) {
        UUID expected = serviceIdByIdentity.get(identity);
        return expected != null && expected.equals(requestDTO.getServiceId());
    }

    @Operation(
            summary = "Register database credentials",
            description = "Stores static database credentials for an org/service pair and registers the database connection with OpenBao's dynamic secrets engine. " +
                    "After registration, callers should use POST /credentials/ephemeral instead of these static credentials. " +
                    "Cannot be used to register credentials for Raum itself. Requires CREDENTIAL_MANAGE."
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Credentials registered — returns orgId and serviceId only; static credentials are not echoed back"),
            @ApiResponse(responseCode = "400", description = "Invalid request body", content = @Content(schema = @Schema(implementation = ErrorResponse.class))),
            @ApiResponse(responseCode = "401", description = "Missing or invalid JWT", content = @Content(schema = @Schema(implementation = ErrorResponse.class))),
            @ApiResponse(responseCode = "403", description = "Insufficient permissions or attempt to register credentials for Raum", content = @Content(schema = @Schema(implementation = ErrorResponse.class)))
    })
    @SecurityRequirement(name = "bearerAuth")
    @PostMapping
    public Mono<BasicCredentialDTO> saveCredentials(@RequestBody CredentialsDTO credentials) {
        return credentialsService.saveNewCredentials(credentials);
    }
}
