apiVersion: 1

contactPoints:
  - orgId: 1
    name: kenoma-email-alerts
    receivers:
      - uid: kenoma-email-receiver
        type: email
        settings:
          addresses: ${GRAFANA_ALERT_EMAIL}
          singleEmail: true
          subject: '{{ template "kenoma.subject" . }}'
          message: '{{ template "kenoma.message" . }}'
        disableResolveMessage: false
